### PR TITLE
Export set and get methods

### LINKED ISSUE #1: Expose set key method and listen to outside changes
It would be nice if the hook exposed its methods to set key values dynamically.

Let's say I have an upload field and I want to set the key with the file's name to the value of the file.
Currently I have to create the hook and specify the key at the very beginning. So I cannot have a handler that sets that key-value pair dynamically.

I could save the key-value into the DB myself but it would be nice if `use-db-keyval` would:
- Expose its set method since it abstracts DB access
- Listen to DB changes and update the return value of the hook if the DB changes externally - in this case through the call to the exposed set method

### PR DESCRIPTION
**Pull request by IgnusG**
Some business logic could update the message when required

```jsx

import { set } from 'use-idb-keyval';

export function fetchQuotes() {
  fetch("best-quotes.fake").then((quote) => set('quote', quote));
}
```

A view component can then display it

```jsx
import useIdb from 'use-idb-keyval';

export function Quote() {
  const [quote] = useIdb('quote');

  return <div>{quote}</div>
}
```

Resolves https://github.com/brandonpittman/use-idb-keyval/issues/1

### CODE REVIEW

**Comment by IgnusG** [comment]
Since the hook state can now be updated externally (which means deleting a value will result in undefined and that is skipped), I was thinking of setting the state to undefined too. Otherwise external subscribers will keep the old value.

This is a breaking change though so not sure if it should be included or split into a separate hook or something different altogether. Any thoughts @brandonpittman?

**Comment by IgnusG** [comment]
An overly simplistic example:

This is how one could use the IDB state in a presentation component

```jsx
import useIdb from 'use-idb-keyval';

export function Quote() {
  const [quote] = useIdb('quote');

  return <div>{quote}</div>
}
```

And then some business logic could update the message when it sees fit

```jsx

import { set } from 'use-idb-keyval';

export function fetchQuotes() {
  fetch("best-quotes.fake").then((quote) => set('quote', quote));
}
```

**Comment by brandonpittman** [comment]
@IgnusG it’s late here in Japan. I’ll look at it closely tomorrow. Probably requires a major version bump, but it looks exciting.

**Comment by IgnusG** [comment]
> @IgnusG it’s late here in Japan. I’ll look at it closely tomorrow. Probably requires a major version bump, but it looks exciting.

No rush. Take your time 🙂

**Comment by brandonpittman** [comment]
@IgnusG I am okay with exposing the underlying set method, but I’m wondering if it’s not better to let the reactivity be left to something like SWR, with it using an exposed get method to refresh itself.

**Comment by IgnusG** [comment]
True, with both exposed you could write your own reactive hook and customize it depending on the use case, but that reduces the library down to an indexdb wrapper instead of a custom react hook. 

On the other hand this is a breaking change and it's possible the non-reactive nature might be desired instead (if the storage data should not overwrite the app data or because of performance concerns). 

Maybe we could introduce a second "reactive" hook and leave the original untouched? (This would probably require the use of named exports instead of default ones - still a breaking change)

**Comment by IgnusG** [comment]
If you disagree though I will remove the sync behavior and just leave the two exports in this PR.

**Comment by brandonpittman** [comment]
@IgnusG for now, I think leaving out the reactivity is best.

**Comment by IgnusG** [comment]
> @IgnusG for now, I think leaving out the reactivity is best.

Done

**Pull request closed without merging**
